dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: IgljC7FsqQ/0Tz6ZmwaaEqvYZGg4WTona7dVE7JdRsSb1qjvHj2KcgQ86JZ7WLMm+B6I8xfLfPCDnBMurrymdk8OEi7H9MBvPblsAKdQ+dQm88DamFfWMH6VtPyEFMjBpYFxbwRwfPC46HNh0v5uCLmfG4xB++ypmcPYJWbGYDRs/X3CXJL8wJZslMGwFOOHp04WbOyMTz1CxkaPfBlO1wtAdodKFNH1096HxivVXCCgGqaIJnYzjCuD0Un7fwihADhNfLJDv2ERzbCEpfYwlOrnhXcA/engNJkMQnjO+DwebF/YtZ/YQpjNKyu0/n/stWYl3pwMe9XCHJaS2DjPoVtE2uOYnTj4Q8ADjahWjoiBEXKxT+pywI/oeAd2bBSQ3uRY0hXy30asrZz96fGaDzDwNuFJmMbfYadI7C7dyDhEhpC8b6LL2SayiJBbjG7c6hcZkn752ScXTSAO8zQf3Fqs4MEEh3FXD9CjrK/CwBMisT2fJOJjQR8sBDhsmjUHubUHvgO4xOMzJAjNeybaTOqJi5MwPl6AL7M2Z0Dl4tz46vCpagg2QtWxfVFe/gWHJLumzmczkcZJCFl3MqXVVx6xta2KVHyamyq0azsd1nUHvsfncXKwGPkF3LbJ9rM2KlGD5OyrHXaHiGlbUEujz1hZSoLjLlUPq7rDcdhLGZ8=