global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#konstantin_kisilesvkiy'
