version: '3.3'
services:
  db:
    image: mongo:${MONGO_VERSION}
    container_name: mongo_${MONGO_VERSION}
    volumes:
      - volume_db:/data/db
    networks:
      - back_net
  ui:
    #build: ../src/ui/docker_build.sh
    container_name: ui_${UI_VERSION}
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    #build: ../src/post-py/docker_build.sh
    container_name: post_${POST_VERSION}
    image: ${USERNAME}/post:${POST_VERSION}
    links:
        - db:post_db
    networks:
      - back_net
      - front_net
  comment:
    #build: ../src/comment/docker_build.sh
    container_name: comment_${COMMENT_VERSION}
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    links:
        - db:comment_db
    networks:
      - back_net
      - front_net

  prometheus:
    build: ../monitoring/prometheus
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    links:
      - blackbox-exporter  
    networks:
      - back_net
      - front_net 

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net  

  mongodb-exporter:
    image: ${USERNAME}/mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://mongodb_exporter:${MONGO_PASS}@db:27017
    networks:
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.17.0
    #dns: 8.8.8.8
    restart: always
    ports:
      - "9115:9115"
    # volumes:
    #   - "/home/yc-user/blackbox-config:/config"
    # command: --config.file=/config/blackbox.yml
    networks:
      - back_net
    

volumes:
  prometheus_data:
  volume_db:

networks:
  back_net:
  front_net:
