version: '3.3'
services:
  db:
    image: mongo:${MONGO_VERSION}
    container_name: mongo_${MONGO_VERSION}
    volumes:
      - volume_db:/data/db
    networks:
      - back_net
  ui:
    #build: ../src/ui/docker_build.sh
    container_name: ui_${UI_VERSION}
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    #build: ../src/post-py/docker_build.sh
    container_name: post_${POST_VERSION}
    image: ${USERNAME}/post:${POST_VERSION}
    links:
        - db:post_db
    networks:
      - back_net
      - front_net
  comment:
    #build: ../src/comment/docker_build.sh
    container_name: comment_${COMMENT_VERSION}
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    links:
        - db:comment_db
    networks:
      - back_net
      - front_net    

volumes:
  volume_db:

networks:
  back_net:
  front_net:
